"""add_user_id_to_challenges

Revision ID: ce7e2e7b4542
Revises: 0001
Create Date: 2026-06-17 19:49:03.070073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce7e2e7b4542'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_challenge_completions_challenge_id'), 'challenge_completions', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_challenge_completions_user_id'), 'challenge_completions', ['user_id'], unique=False)
    op.add_column('challenges', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_challenges_user_id'), 'challenges', ['user_id'], unique=False)
    op.create_foreign_key(None, 'challenges', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('eco_scores', 'transport_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('eco_scores', 'energy_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('eco_scores', 'food_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('eco_scores', 'shopping_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.create_index(op.f('ix_habit_logs_habit_id'), 'habit_logs', ['habit_id'], unique=False)
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    op.drop_index('ix_users_google_id', table_name='users')
    op.create_unique_constraint(None, 'users', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_google_id', 'users', ['google_id'], unique=True)
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_habit_logs_habit_id'), table_name='habit_logs')
    op.alter_column('eco_scores', 'shopping_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('eco_scores', 'food_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('eco_scores', 'energy_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('eco_scores', 'transport_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.drop_constraint(None, 'challenges', type_='foreignkey')
    op.drop_index(op.f('ix_challenges_user_id'), table_name='challenges')
    op.drop_column('challenges', 'user_id')
    op.drop_index(op.f('ix_challenge_completions_user_id'), table_name='challenge_completions')
    op.drop_index(op.f('ix_challenge_completions_challenge_id'), table_name='challenge_completions')
    # ### end Alembic commands ###
